#!/usr/bin/env python3
"""List likely user-visible shell literals not routed through translate()."""

from __future__ import annotations

import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "reports" / "zh-CN-uncovered-hardcoded-strings.md"
SHELL_LITERAL = re.compile(r"\b(?:dialog|whiptail|echo|printf)\b.*(?:\"[^\"]*[A-Za-z][^\"]*\"|'[^']*[A-Za-z][^']*')")


def main() -> int:
    findings: list[tuple[str, int, str]] = []
    for path in sorted([*ROOT.glob("*.sh"), *(ROOT / "scripts").rglob("*.sh")]):
        for line_no, line in enumerate(path.read_text(encoding="utf-8", errors="replace").splitlines(), start=1):
            stripped = line.strip()
            if "translate" in stripped or stripped.startswith("#") or not SHELL_LITERAL.search(stripped):
                continue
            # Only direct dialogs or literal echo messages are useful review
            # candidates. Formatting strings, variables and configuration file
            # writes create too many false positives to call them untranslated UI.
            if "printf" in stripped or "$" in stripped:
                continue
            if any(token in stripped for token in ("> /", ">>", "echo \"active\"", "echo \"inactive\"", "echo \"auto\"", "echo \"manual\"", "echo '{}'")):
                continue
            findings.append((str(path.relative_to(ROOT)), line_no, stripped))
    OUTPUT.parent.mkdir(exist_ok=True)
    lines = [
        "# Likely unlocalized hard-coded shell strings",
        "",
        "Generated by `tools/report_uncovered_strings.py`. This is a conservative static-review list, not a runtime proof: multiline dialogs can begin on a different line and some entries are logs, command examples, or non-English legacy strings.",
        "",
        f"Count: {len(findings)}",
        "",
        "| File | Line | Source |",
        "| --- | ---: | --- |",
    ]
    for path, line_no, source in findings:
        source = source.replace("|", "\\|").replace("`", "'")
        lines.append(f"| `{path}` | {line_no} | `{source}` |")
    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {len(findings)} findings to {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
