#!/usr/bin/env python3
"""Validate ProxMenux zh-CN catalogs and write an auditable fallback list."""

from __future__ import annotations

import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
REPORTS = ROOT / "reports"
PLACEHOLDER_RE = re.compile(r"\{[A-Za-z_][A-Za-z0-9_]*\}")


def flatten(node: dict, prefix: str = "") -> dict[str, str]:
    result: dict[str, str] = {}
    for key, value in node.items():
        path = f"{prefix}.{key}" if prefix else key
        if isinstance(value, dict):
            result.update(flatten(value, path))
        else:
            result[path] = "" if value is None else str(value)
    return result


def placeholders(text: str) -> list[str]:
    return sorted(PLACEHOLDER_RE.findall(text))


def load_pair(source_path: str, target_path: str, flat: bool) -> tuple[str, dict[str, str], dict[str, str]]:
    source = json.loads((ROOT / source_path).read_text(encoding="utf-8"))
    target = json.loads((ROOT / target_path).read_text(encoding="utf-8"))
    return target_path, source if flat else flatten(source), target if flat else flatten(target)


def main() -> int:
    pairs = [
        load_pair("AppImage/messages/en/common.json", "AppImage/messages/zh-CN/common.json", False),
        load_pair("lang/es.json", "lang/zh-CN.json", True),
    ]
    REPORTS.mkdir(exist_ok=True)
    summary: dict[str, dict] = {}
    fallback_lines = [
        "# zh-CN English fallback / unlocalized-value list",
        "",
        "Generated by `tools/validate_zh_cn.py`. Entries below have the same non-empty value as the English source. Some are intentionally universal names, protocols, commands or units; review the list before treating an entry as a translation defect.",
        "",
    ]
    valid = True
    for target_path, source, target in pairs:
        missing = sorted(set(source) - set(target))
        extra = sorted(set(target) - set(source))
        empty = sorted(
            key for key in source
            if key in target and source[key] and not target[key]
        )
        placeholders_bad = sorted(
            key for key in source
            if key in target and placeholders(source[key]) != placeholders(target[key])
        )
        unchanged = sorted(key for key in source if source[key] and source[key] == target.get(key))
        summary[target_path] = {
            "source_keys": len(source), "target_keys": len(target), "missing_keys": missing,
            "extra_keys": extra, "unexpected_empty_values": empty,
            "placeholder_mismatches": placeholders_bad, "english_fallback_or_universal_values": unchanged,
        }
        # A partial catalog is valid by design: scripts/utils.sh and the
        # Monitor provider fall back to the original English value when a
        # zh-CN key is absent.  Missing keys remain in the report so future
        # contributors can translate them without masking coverage gaps.
        valid = valid and not (extra or empty or placeholders_bad)
        fallback_lines.extend([f"## `{target_path}` ({len(unchanged)} entries)", ""])
        for key in unchanged:
            fallback_lines.append(f"- `{key}` — `{source[key].replace('`', "'")}`")
        fallback_lines.append("")
    (REPORTS / "zh-CN-validation.json").write_text(json.dumps(summary, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    (REPORTS / "zh-CN-english-fallback.md").write_text("\n".join(fallback_lines).rstrip() + "\n", encoding="utf-8")
    print("PASS" if valid else "FAIL")
    return 0 if valid else 1


if __name__ == "__main__":
    raise SystemExit(main())
